/**
 * What an agent must read before it may touch this repository, and what that
 * costs on every task.
 *
 * Everything in the must-read set is paid for by every agent on every task,
 * forever. That makes it a budget like bundle size rather than a free resource,
 * and the failure mode is quiet: a contract grows a paragraph at a time, nobody
 * notices, and a year later the cheapest task carries eleven thousand tokens of
 * prose before it starts.
 *
 * Unlike provenance, this IS a gate. A budget is a forward-looking rule about
 * files the team controls, so it can be true from the day it lands — and it lands
 * at what the repository costs today plus headroom, which is the same ratchet
 * used everywhere else here. Nothing is red on day one; growth is what turns it
 * red.
 *
 * Token counts are an estimate — characters over four, the usual rule for English
 * and code. Enough for a trend line and a budget, not for billing, and the
 * generated runner says so rather than letting somebody quote it as exact.
 */

const tokens = (text) => (text ? Math.round(text.length / 4) : 0)

/**
 * @param {object} input
 * @param {(path: string) => string|undefined} input.read  repository-relative
 * @param {string[]} input.alwaysOn  paths an agent reads on every task
 * @param {number} [input.headroom]  fraction of slack above today's cost
 */
export function generateBudget({ read, alwaysOn, headroom = 0.25 }) {
  const entries = []
  for (const path of alwaysOn) {
    const text = read(path)
    if (text === undefined) continue
    const cost = tokens(text)
    entries.push({
      path,
      tokens: cost,
      // Rounded to something a person would have chosen, so the number in the
      // file reads as a decision rather than as a measurement with a decimal.
      budget: Math.max(500, Math.ceil((cost * (1 + headroom)) / 100) * 100),
    })
  }
  if (!entries.length) return undefined

  const total = entries.reduce((n, e) => n + e.tokens, 0)
  return {
    manifest: {
      schemaVersion: 1,
      _: [
        'The must-read set: what an agent reads before it may touch this repository.',
        '',
        'Each budget started at what the file cost on the day this landed, plus a quarter.',
        'Nothing was red then; growth is what turns it red. Raising a budget is a decision',
        'somebody makes on purpose, which is the point — a contract grows a paragraph at a',
        'time and nobody notices until the cheapest task carries a chapter.',
        '',
        'When a budget does trip, the answer is rarely a shorter sentence. It is usually that',
        'something in here is not must-read: detail an agent needs sometimes belongs in a skill',
        'it reaches for, not in the text it carries always.',
      ],
      totalTokens: total,
      totalBudget: entries.reduce((n, e) => n + e.budget, 0),
      files: entries,
    },
    runner: RUNNER,
    total,
  }
}

const RUNNER = `/**
 * The must-read set, measured against its budget.
 *
 * Everything here is paid for by every agent on every task. Generated by
 * AI FactoryFit from what this repository cost when the gate landed; \`.ds/context-budget.json\`
 * holds the numbers and the reasoning.
 *
 * Token counts are an estimate — characters over four. A trend line and a budget,
 * not billing: compare runs, do not quote it as exact.
 *
 *   node scripts/gate/context.mjs
 */
import { readFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '..', '..')
const manifest = JSON.parse(readFileSync(join(repo, '.ds', 'context-budget.json'), 'utf8'))

const tokens = (text) => (text ? Math.round(text.length / 4) : 0)

const rows = manifest.files.map(f => {
  const at = join(repo, f.path)
  if (!existsSync(at)) return { ...f, now: null }
  return { ...f, now: tokens(readFileSync(at, 'utf8')) }
})

const over = rows.filter(r => r.now !== null && r.now > r.budget)
const gone = rows.filter(r => r.now === null)
const total = rows.reduce((n, r) => n + (r.now ?? 0), 0)

console.log('\\ncontext budget — what every agent pays on every task\\n')
for (const r of rows) {
  const state = r.now === null ? 'MISSING' : r.now > r.budget ? 'OVER' : 'ok'
  console.log(\`  \${String(r.now ?? '—').padStart(6)} / \${String(r.budget).padEnd(6)} \${state.padEnd(8)} \${r.path}\`)
}
console.log(\`\\n  \${total} token(s) against a budget of \${manifest.totalBudget}\`)

if (gone.length) {
  console.log('\\n  A file in the manifest is gone. Either it moved and the manifest is stale, or')
  console.log('  the must-read set shrank and nobody said so — both are worth a minute.')
}
if (over.length) {
  console.log('\\n  Over budget. The answer is rarely a shorter sentence: detail an agent needs')
  console.log('  SOMETIMES belongs in a skill it reaches for, not in the text it carries ALWAYS.')
  console.log('  Raising the number in .ds/context-budget.json is a decision, and a fine one —')
  console.log('  it just has to be made rather than drifted into.')
}
process.exit(over.length ? 1 : 0)
`
