/**
 * The delivery loop for one repository, with its gates set by what that
 * repository can actually support.
 *
 * The reference models all draw the same picture — define, plan, build, verify,
 * review, ship — and then differ entirely in where the human gates sit. One
 * regulated system puts four of them in and proves every change against the
 * engine it is replacing; a team shipping a marketing site would be strangled by
 * the same shape. Copying the picture is how a consultant installs somebody
 * else's operating model.
 *
 * So the stages are the same everywhere and the GATES ARE DERIVED. A repository
 * where nothing stops a bad turn gets a person at every stage, because there is
 * nothing else. One that scores its own output and runs unattended gets a person
 * at the gate that matters and proceeds elsewhere. The audit already computes
 * which of the three that is; this reads it rather than asking.
 *
 * What this is NOT: an agent framework. It runs the deterministic parts — the
 * gate, the evidence pack — and stops where a person is required, saying what
 * they are being asked to approve. Whatever writes the code is the team's choice
 * and is invoked by them, not by us.
 */

/** The stages, which do not vary. What varies is who has to say yes. */
const STAGES = [
  { id: 'define', what: 'the requirement becomes a spec somebody agreed',
    runs: [], produces: 'a spec' },
  { id: 'plan', what: 'the spec becomes a change somebody can review',
    runs: [], produces: 'a work plan' },
  { id: 'build', what: 'the change is written, in this repository\'s idiom',
    runs: ['gate:edit'], produces: 'a change set' },
  { id: 'verify', what: 'the change is proved, not asserted',
    runs: ['gate:commit', 'evidence'], produces: 'an evidence pack' },
  { id: 'review', what: 'a person reads the evidence rather than the diff',
    runs: [], produces: 'a verdict' },
  { id: 'ship', what: 'the change reaches production',
    runs: ['gate:ci'], produces: 'a release' },
]

/**
 * Where a person must say yes, given what the repository supports.
 *
 * The reasoning is stated per gate, because "why is there a gate here" is the
 * first question a team asks and "the framework says so" is the wrong answer.
 */
const GATES = {
  assisted: {
    at: ['define', 'plan', 'verify', 'review', 'ship'],
    why: 'Nothing here stops a bad turn on its own, so a person is the only check at every stage. '
      + 'This is not a judgement about the team; it is what the measurement found.',
  },
  'delegated-review': {
    at: ['define', 'review', 'ship'],
    why: 'The output can be scored and something checks it without being asked, so the middle of the '
      + 'loop does not need a person. The intent and the verdict still do.',
  },
  'gated-autonomous': {
    at: ['define', 'ship'],
    why: 'Something stops a bad turn with nobody watching and the rules are measured to improve the '
      + 'output, so the loop proceeds by default. The gate at the end is a person who has decided not '
      + 'to intervene yet, which is not the same as no person.',
  },
  none: {
    at: ['define', 'plan', 'build', 'verify', 'review', 'ship'],
    why: 'There is no contract an agent can read here, so nothing about this loop is delegable yet. '
      + 'Every stage is a person until that changes.',
  },
}

export function generateLoop({ delegation, name, hasEvidence, hasGate }) {
  const level = delegation?.supported ?? 'none'
  const gates = GATES[level] ?? GATES.none
  const missing = delegation?.levels?.find(l => !l.met)

  const stages = STAGES.map(s => ({
    ...s,
    // A stage cannot run a check the repository does not have. Listing one that
    // is absent produces a loop that fails on its first run for a reason nobody
    // put there.
    runs: s.runs.filter(r => (r === 'evidence' ? hasEvidence : hasGate)),
    gate: gates.at.includes(s.id),
  }))

  const definition = {
    schemaVersion: 1,
    project: name,
    derivedFrom: {
      delegation: level,
      why: gates.why,
      toRemoveTheNextGate: missing
        ? { level: missing.id, needs: missing.missing.map(m => m.is) }
        : 'nothing; this repository supports the highest level measured here',
    },
    stages,
  }

  return { definition, runner: RUNNER, level, gateCount: gates.at.length }
}

const RUNNER = `/**
 * The delivery loop, run one stage at a time.
 *
 * Generated by AI FactoryFit. The stages are the same in every project; the gates
 * came from what THIS repository was measured to support, and \`.ds/loop.json\`
 * says which level that was and what would move it.
 *
 * This runs the deterministic parts and stops where a person is required. It does
 * not write code and does not call an agent: whatever does that is the team's
 * choice, and a loop that owns it is a loop nobody can substitute into.
 *
 *   node scripts/loop/run.mjs                 what stage is next, and why
 *   node scripts/loop/run.mjs <stage>         run one stage's checks
 *   node scripts/loop/run.mjs <stage> --pass  record that a human gate was passed
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'

const here = dirname(fileURLToPath(import.meta.url))
const repo = join(here, '..', '..')
const definition = JSON.parse(readFileSync(join(repo, '.ds', 'loop.json'), 'utf8'))

const [wanted, ...flags] = process.argv.slice(2)
const passing = flags.includes('--pass')

// One id across the whole run, so a stage's output can be tied to the stage
// before it. This is the shape a trace has, written to a file rather than sent to
// a collector — there is no collector here, and pretending otherwise would make
// the loop depend on infrastructure this repository does not have.
const statePath = join(repo, '.ds', 'loop-state.json')
const state = existsSync(statePath) ? JSON.parse(readFileSync(statePath, 'utf8')) : { run: null, spans: [] }
const record = (span) => {
  state.spans.push(span)
  mkdirSync(dirname(statePath), { recursive: true })
  writeFileSync(statePath, JSON.stringify(state, null, 2) + '\\n')
}

const CHECKS = {
  'gate:edit': ['scripts/gate/run.mjs', 'edit'],
  'gate:commit': ['scripts/gate/run.mjs', 'commit'],
  'gate:ci': ['scripts/gate/run.mjs', 'ci'],
  evidence: ['scripts/gate/../../node_modules/.bin/ds', 'evidence', '.'],
}

const run = (check) => {
  const argv = CHECKS[check]
  if (!argv) return { check, verdict: 'unknown check' }
  const bin = join(repo, argv[0])
  if (!existsSync(bin)) return { check, verdict: 'not installed' }
  try {
    execFileSync(process.execPath, [bin, ...argv.slice(1)], { cwd: repo, stdio: 'inherit' })
    return { check, verdict: 'passed' }
  } catch {
    return { check, verdict: 'failed' }
  }
}

if (!wanted) {
  console.log(\`\\nloop: \${definition.project} — gates set by the \${definition.derivedFrom.delegation} level\\n\`)
  console.log('  ' + definition.derivedFrom.why.replace(/(.{72}\\s)/g, '$1\\n  '))
  console.log('')
  for (const s of definition.stages) {
    const done = state.spans.some(sp => sp.stage === s.id && sp.verdict === 'passed')
    console.log(\`  \${done ? '✓' : ' '} \${s.id.padEnd(8)} \${s.gate ? 'GATE — a person says yes' : 'proceeds'}\${s.runs.length ? '  · runs ' + s.runs.join(', ') : ''}\`)
  }
  const next = definition.derivedFrom.toRemoveTheNextGate
  if (typeof next === 'object') {
    console.log(\`\\n  To remove a gate, this repository needs \${next.level}: \${next.needs.join('; ')}.\`)
    console.log('  Gates come off when the thing that would have caught it exists, not before.')
  }
  process.exit(0)
}

const stage = definition.stages.find(s => s.id === wanted)
if (!stage) {
  console.error(\`loop: no stage "\${wanted}". Stages: \${definition.stages.map(s => s.id).join(', ')}\`)
  process.exit(2)
}

state.run ??= \`run-\${state.spans.length + 1}\`

if (stage.gate && !passing) {
  const results = stage.runs.map(run)
  for (const r of results) record({ run: state.run, stage: stage.id, ...r })
  const failed = results.filter(r => r.verdict === 'failed')
  console.log(\`\\n\${stage.id}: \${stage.what}\`)
  for (const r of results) console.log(\`  \${r.verdict.padEnd(14)} \${r.check}\`)
  console.log(\`\\n  GATE. \${failed.length ? 'Checks failed above; a person should not be asked to approve this yet.' : 'The checks passed. A person is being asked to approve ' + stage.produces + '.'}\`)
  console.log(\`  Record it with:  node scripts/loop/run.mjs \${stage.id} --pass\`)
  process.exit(failed.length ? 1 : 0)
}

const results = stage.runs.map(run)
for (const r of results) record({ run: state.run, stage: stage.id, ...r })
if (passing) record({ run: state.run, stage: stage.id, check: 'human gate', verdict: 'passed' })

console.log(\`\\n\${stage.id}: \${stage.what}\`)
for (const r of results) console.log(\`  \${r.verdict.padEnd(14)} \${r.check}\`)
if (passing) console.log('  passed         human gate')
if (!results.length && !passing) console.log('  nothing deterministic to run here; this stage is people and a document')
process.exit(results.some(r => r.verdict === 'failed') ? 1 : 0)
`
