/**
 * What an agent may run here, taken from what this repository already runs.
 *
 * A permission list is the one piece of configuration where copying somebody
 * else's is worse than having none. Too tight and every task stops on a prompt
 * until a person turns the whole thing off; too loose and the setting is
 * decoration. Both failures end in the same place — a project where permissions
 * exist and mean nothing.
 *
 * So this asks the repository. A command in its own package scripts is a command
 * the team runs all day; allowing those costs nothing and buys back every prompt
 * that would have interrupted a task for `npm test`. Everything else stays
 * unlisted, which is not a ban — it is the prompt still happening, for the things
 * nobody has decided about yet.
 *
 * The deny list is the opposite: short, and not derived at all. These are the
 * commands whose damage is not undone by review, and no measurement of a
 * repository makes `rm -rf` reasonable in it.
 */

/**
 * Commands whose consequences outlive the session that ran them. Denied
 * regardless of what the project does, because a repository that force-pushes in
 * a script is a repository with a bad script, not a case for allowing it.
 */
const NEVER = [
  { rule: 'Bash(rm -rf:*)', why: 'a deletion no review recovers' },
  { rule: 'Bash(git push --force:*)', why: 'rewrites a history other people have' },
  { rule: 'Bash(git push --force-with-lease:*)', why: 'the safer force is still a force, and the gate has not run' },
  { rule: 'Bash(git reset --hard:*)', why: 'discards work that was never committed and cannot be recovered' },
  { rule: 'Bash(npm publish:*)', why: 'publishing is a release, and a release is a person\'s decision' },
  { rule: 'Bash(curl:*)', why: 'fetching and running something from the network is how a session becomes somebody else\'s' },
  { rule: 'Bash(chmod 777:*)', why: 'a permission nobody meant to grant, on a machine nobody is watching' },
  { rule: 'Read(./.env)', why: 'a secret read into context is a secret in a transcript' },
  { rule: 'Read(./.env.*)', why: 'as above, for every variant' },
  { rule: 'Read(./**/*.pem)', why: 'a private key read into context is a leaked private key' },
]

/**
 * @param {object} input
 * @param {Record<string,string>} input.scripts  the project's package scripts
 * @param {string[]} input.tools  binaries found in the toolchain audit
 * @param {boolean} input.hasGate  whether the gate is installed here
 */
export function generatePermissions({ scripts = {}, tools = [], hasGate = false }) {
  const allow = []
  const seen = new Set()
  const add = (rule, why) => { if (!seen.has(rule)) { seen.add(rule); allow.push({ rule, why }) } }

  // The project's own scripts, one rule each. This is the whole point: a task
  // stopping on a prompt for `npm run lint` in a repository whose CI runs
  // `npm run lint` on every push is a prompt nobody learns anything from.
  for (const name of Object.keys(scripts)) {
    // A script that publishes, deploys or releases is exactly the kind a person
    // should still be asked about, whatever it is called locally.
    if (/publish|release|deploy|prod|migrate|reset|destroy/i.test(name)) continue
    add(`Bash(npm run ${name}:*)`, `this project's own \`${name}\` script`)
  }

  // Reading anything, because an agent that cannot read cannot conform. The cost
  // of a wrong read is a wasted turn; the cost of a blind write is the defect
  // this whole tool exists to prevent.
  add('Read(./**)', 'an agent that cannot read the repository cannot match it')

  if (hasGate) {
    add('Bash(node scripts/gate/run.mjs:*)', 'the gate, which is the thing that catches a bad edit')
    add('Bash(node evals/run.mjs:*)', 'the evals, which ask whether the gate would notice')
  }

  for (const tool of tools) {
    if (/eslint|oxlint|biome|prettier|stylelint/.test(tool)) add(`Bash(npx ${tool}:*)`, `${tool} is already in this toolchain`)
    if (/vitest|jest/.test(tool)) add(`Bash(npx ${tool}:*)`, `${tool} is already in this toolchain`)
  }

  add('Bash(git status:*)', 'reading state, which changes nothing')
  add('Bash(git diff:*)', 'reading state, which changes nothing')
  add('Bash(git log:*)', 'reading state, which changes nothing')

  return {
    permissions: {
      allow: allow.map(a => a.rule),
      deny: NEVER.map(n => n.rule),
    },
    reasoning: {
      _: [
        'Generated by AI FactoryFit from what this repository already runs.',
        '',
        'ALLOW is derived: a command in this project\'s own package scripts is a command the',
        'team runs all day, and a task stopping on a prompt for `npm test` in a repository',
        'whose CI runs `npm test` on every push is a prompt nobody learns anything from.',
        '',
        'What is NOT on the allow list is not banned. It prompts — which is the correct',
        'answer for anything nobody has decided about yet.',
        '',
        'DENY is not derived and should not be. These are commands whose damage outlives the',
        'session, and no measurement of a repository makes `rm -rf` reasonable in it. Scripts',
        'that publish, deploy, release or migrate were deliberately left off the allow list',
        'even where this project has them, because those are decisions rather than tasks.',
      ],
      allow,
      deny: NEVER,
    },
  }
}
